fix workspace

diff --git a/chdistro b/chdistro
--- a/chdistro
+++ b/chdistro
@@ -1,27 +1,28 @@
-#!/bin/bash
+#!/bin/sh
 
 # Help
-if [ $# -eq 0 ] || [[ $1 = "--help" ]]; then
+if [ $# -eq 0 ] || [ $1 = "--help" ]; then
     echo "chdistro ROS_DISTRO [WORKSPACE_DIR]"
     exit
 fi
 
-# Shell
 suffix=".bash"
-if [[ $SHELL = "/bin/zsh" ]]; then
+if [ $SHELL = "/bin/zsh" ]; then
     suffix=".zsh"
 fi
-echo $suffix
 
-# Worksspace
 workspace="$HOME/ros/$1"
-if [ $# -ne 2 ]; then
+if [ $# -eq 2 ]; then
     workspace=$2
 fi
-echo $workspace
+
+if [ ! -e /opt/ros/$1 ]; then
+    echo "invalid ROS_DISTRO"
+    exit 1
+fi
 
 # ROS2
-if [[ $1 = "eloquent" ]] || [[ $1 = "dashing" ]]; then
+if [ $1 = "eloquent" ] || [ $1 = "dashing" ]; then
     source /opt/ros/$1/setup$suffix
     export ROS_HOME=~/.ros
     export ROS_LOCALHOST_ONLY=1
@@ -30,8 +31,8 @@ if [[ $1 = "eloquent" ]] || [[ $1 = "dashing" ]]; then
         . $workspace/install/local_setup$suffix
         export ROS_WORKSPACE=$workspace
     fi
-    # ROS1
-elif [[ $1 = "melodic" ]] || [[ $1 = "kinetic" ]]; then
+# ROS1
+elif [ $1 = "melodic" ] || [ $1 = "kinetic" ]; then
     source /opt/ros/$1/setup$suffix
     export ROS_HOME=~/.ros
     source `catkin locate --shell-verbs`
@@ -42,8 +43,5 @@ elif [[ $1 = "melodic" ]] || [[ $1 = "kinetic" ]]; then
         catkin source
         popd
     fi
-else
-    echo "invalid ROS_DISTRO"
-    exit 1
 fi
 env | grep ROS
